| |<font size="5">Data Encoding ترميز البيانات </font>|
|-:|-:|
|<img src="https://www.genome.gov/sites/default/files/media/images/2019-03/2.4.8.6.6.4_ENCODE.jpg" width=400></img>||
||<font size="4"> تحميل البيانات </font>| 
||<font size="4">  تنويع استراتيجيات ترميز البيانات الترتيبية</font>| 


- ترميز البينات بالطريقة التي تعرضنا اليها سابقا  افرزت علاقة تفاضلية فيما بين البيانات


In [1]:
#تحميل البيانات 
import pandas as pd
# read_csv(..., nrows=999999)
df= pd.read_csv("../data/HousePrice3.csv", index_col=0)
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0          60       RL         65.0     8450   Pave   NaN      Reg   
1          20       RL         80.0     9600   Pave   NaN      Reg   
2          60       RL         68.0    11250   Pave   NaN      IR1   
3          70       RL         60.0     9550   Pave   NaN      IR1   
4          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities LotConfig  ... MiscVal YrSold SaleType SaleCondition  \
0         Lvl    AllPub    Inside  ...       0   2008       WD        Normal   
1         Lvl    AllPub       FR2  ...       0   2007       WD        Normal   
2         Lvl    AllPub    Inside  ...       0   2008       WD        Normal   
3         Lvl    AllPub    Corner  ...       0   2006       WD       Abnorml   
4         Lvl    AllPub       FR2  ...       0   2008       WD        Normal   

  SalePrice TotalSF  TotalPorchSF  TotalBath      SnMoSold      CsMoSold  
0    208500    2566            61        3.5  8.660254e-01  5.000000e-01  
1    181500    2524             0        2.5  5.000000e-01 -8.660254e-01  
2    223500    2706            42        3.5 -1.000000e+00 -1.836970e-16  
3    140000    2473           307        2.0  8.660254e-01  5.000000e-01  
4    250000    3343            84        3.5 -2.449294e-16  1.000000e+00  

[5 rows x 72 columns]

![](https://image.flaticon.com/icons/png/128/3079/3079166.png)

In [2]:
# labelEncoder    الترميز 
from sklearn.preprocessing import LabelEncoder
lblEnc=LabelEncoder()
df["HouseStyle_Enc"]=lblEnc.fit_transform(df.HouseStyle)


In [3]:
df[["HouseStyle_Enc"]].sample(3)
#  لا يمكن الجزم بأن قيمة 3 هي اكبر من 0 إلا إذا تعمدنا ذلك خلال التريمز وإلا فوجب  الحيطة

HouseStyle_Enc
1236               5
1117               2
768                2

In [4]:
df.LotShape.unique()

array(['Reg', 'IR1', 'IR2', 'IR3'], dtype=object)

In [5]:
#OverAllQua فإذا ما قارنا ذلك بالقيم الخاصية 
# يتضح الفرق بينهما
df.OverallQual.unique()

array([ 7,  6,  8,  5,  9,  4, 10,  3,  1,  2])

 - يتعرض الترميز الجديد إلى تلك الخصائص التي لا تفاضل فيما بين قيم الترميز فيها 

In [6]:
df.select_dtypes(exclude="number").columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [7]:
df.sample(3)

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
861          190       RL         75.0    11625   Pave   NaN      Reg   
1314          20       RL         60.0     8190   Pave   NaN      Reg   
114           70       RL         61.0     7259   Pave   NaN      IR1   

     LandContour Utilities LotConfig  ... YrSold SaleType SaleCondition  \
861          Lvl    AllPub    Inside  ...   2010       WD        Normal   
1314         Lvl    AllPub    Inside  ...   2007       WD        Normal   
114          Lvl    AllPub    Inside  ...   2007       WD        Normal   

     SalePrice TotalSF TotalPorchSF  TotalBath  SnMoSold  CsMoSold  \
861     131500    2078            0        2.5  0.866025 -0.500000   
1314    119000    1896           36        2.0 -0.866025  0.500000   
114     259500    3348            0        3.5 -0.500000 -0.866025   

      HouseStyle_Enc  
861                2  
1314               2  
114                5  

[3 rows x 73 columns]

In [8]:

for col in df.select_dtypes(exclude="number").columns:
  print(f" {col:-<50} :   {df[col].unique()} & Mising Values |({df[col].isna().sum()/df.shape[0]:.3}) " )

 MSZoning------------------------------------------ :   ['RL' 'RM' 'C (all)' 'FV' 'RH'] & Mising Values |(0.0) 
 Street-------------------------------------------- :   ['Pave' 'Grvl'] & Mising Values |(0.0) 
 Alley--------------------------------------------- :   [nan 'Grvl' 'Pave'] & Mising Values |(0.937) 
 LotShape------------------------------------------ :   ['Reg' 'IR1' 'IR2' 'IR3'] & Mising Values |(0.0) 
 LandContour--------------------------------------- :   ['Lvl' 'Bnk' 'Low' 'HLS'] & Mising Values |(0.0) 
 Utilities----------------------------------------- :   ['AllPub' 'NoSeWa'] & Mising Values |(0.0) 
 LotConfig----------------------------------------- :   ['Inside' 'FR2' 'Corner' 'CulDSac' 'FR3'] & Mising Values |(0.0) 
 LandSlope----------------------------------------- :   ['Gtl' 'Mod' 'Sev'] & Mising Values |(0.0) 
 Neighborhood-------------------------------------- :   ['CollgCr' 'Veenker' 'Crawfor' 'NoRidge' 'Mitchel' 'Somerst' 'NWAmes'
 'OldTown' 'BrkSide' 'Sawyer' 

--   $$\large \text { كل القيم التي لا تشهد تغييرا في بيانتها وجب الاستغناء عنها}$$

In [9]:
for col in df.select_dtypes(exclude="number").columns:
  if df[col].nunique()<2:
    print(f" {col:-<30} {df[col].nunique()}")

- LotShape   لنفترض أن لا تفاضل فيما بين القيم التي تحتويها الخاصية شكل العقار 
-إذا فترميزها لا يفيدنا ، لذا سنلتتجئ إلى  الترميز الأفقي 
- لتبسيط العملية سيتم الاقتصار على خصائص أقل للتوضيح


In [10]:

df_Enc=df[["LotShape","LandSlope" ,"CentralAir" ,"OverallQual"]].sample(15, random_state=1)
df_Enc

LotShape LandSlope CentralAir  OverallQual
1379      Reg       Gtl          Y            5
1359      Reg       Gtl          Y            9
1094      Reg       Gtl          Y            5
920       IR1       Gtl          Y            6
37        Reg       Gtl          Y            5
1228      Reg       Gtl          Y            9
1274      Reg       Gtl          Y            5
91        Reg       Gtl          Y            5
1273      IR1       Gtl          Y            6
1133      IR1       Gtl          Y            8
424       Reg       Gtl          Y            6
1100      Reg       Gtl          N            2
464       Reg       Mod          Y            5
1050      IR1       Gtl          Y            7
525       Reg       Gtl          Y            7

In [11]:
df_Enc.keys()

Index(['LotShape', 'LandSlope', 'CentralAir', 'OverallQual'], dtype='object')

In [12]:
from sklearn.preprocessing import LabelEncoder
lblEnc=LabelEncoder()
df_Enc["CentralAir"]=lblEnc.fit_transform(df_Enc.CentralAir)
df_Enc

LotShape LandSlope  CentralAir  OverallQual
1379      Reg       Gtl           1            5
1359      Reg       Gtl           1            9
1094      Reg       Gtl           1            5
920       IR1       Gtl           1            6
37        Reg       Gtl           1            5
1228      Reg       Gtl           1            9
1274      Reg       Gtl           1            5
91        Reg       Gtl           1            5
1273      IR1       Gtl           1            6
1133      IR1       Gtl           1            8
424       Reg       Gtl           1            6
1100      Reg       Gtl           0            2
464       Reg       Mod           1            5
1050      IR1       Gtl           1            7
525       Reg       Gtl           1            7

## Get_Dummies

In [13]:
pd.get_dummies(df_Enc, columns=['LotShape'], prefix = ['Shape'])


LandSlope  CentralAir  OverallQual  Shape_IR1  Shape_Reg
1379       Gtl           1            5      False       True
1359       Gtl           1            9      False       True
1094       Gtl           1            5      False       True
920        Gtl           1            6       True      False
37         Gtl           1            5      False       True
1228       Gtl           1            9      False       True
1274       Gtl           1            5      False       True
91         Gtl           1            5      False       True
1273       Gtl           1            6       True      False
1133       Gtl           1            8       True      False
424        Gtl           1            6      False       True
1100       Gtl           0            2      False       True
464        Mod           1            5      False       True
1050       Gtl           1            7       True      False
525        Gtl           1            7      False       True

In [14]:
# التعميم
df_Enc= pd.get_dummies(df_Enc, prefix = ['Shape', "Slope"])
df_Enc

CentralAir  OverallQual  Shape_IR1  Shape_Reg  Slope_Gtl  Slope_Mod
1379           1            5      False       True       True      False
1359           1            9      False       True       True      False
1094           1            5      False       True       True      False
920            1            6       True      False       True      False
37             1            5      False       True       True      False
1228           1            9      False       True       True      False
1274           1            5      False       True       True      False
91             1            5      False       True       True      False
1273           1            6       True      False       True      False
1133           1            8       True      False       True      False
424            1            6      False       True       True      False
1100           0            2      False       True       True      False
464            1            5      False       True      False       True
1050           1            7       True      False       True      False
525            1            7      False       True       True      False

- OverallQual يلاحظ عدم  ترميز البيانات الرقمية لعمود 

In [15]:
#LandSlope  أما إذا أخذنا بعين الاعتبار درجة انحناء الأرض التي بني عليها العقار 
# يصبح من الضروري ترتيب قيم الخاصية المذكورة اعلاه كالتالي 
df_Enc=df[["LotShape","LandSlope" ,"CentralAir" ,"OverallQual"]].sample(15, random_state=1)
df_Enc.LandSlope.unique(), df_Enc.CentralAir.unique()


(array(['Gtl', 'Mod'], dtype=object), array(['Y', 'N'], dtype=object))

In [16]:
df_Enc.head(3)

LotShape LandSlope CentralAir  OverallQual
1379      Reg       Gtl          Y            5
1359      Reg       Gtl          Y            9
1094      Reg       Gtl          Y            5

In [17]:
dic_CentralAir={"Y":1, "N":0}
dic_LandSlope={'Gtl':2, 'Mod':1, 'Sev':0}

df_Enc["CentralAir"]=df_Enc.CentralAir.map(dic_CentralAir)
df_Enc["LandSlope"]=df_Enc.LandSlope.map(dic_LandSlope)
df_Enc.head()

LotShape  LandSlope  CentralAir  OverallQual
1379      Reg          2           1            5
1359      Reg          2           1            9
1094      Reg          2           1            5
920       IR1          2           1            6
37        Reg          2           1            5

In [18]:
pd.get_dummies(df_Enc, prefix = 'Shape').head()


LandSlope  CentralAir  OverallQual  Shape_IR1  Shape_Reg
1379          2           1            5      False       True
1359          2           1            9      False       True
1094          2           1            5      False       True
920           2           1            6       True      False
37            2           1            5      False       True

##  OneHotEncoder ترميز   To implement and checl here
 

In [22]:
df_OneHotEncoder=df[["LotShape","LandSlope" ,"CentralAir" ,"OverallQual"]].sample(15, random_state=1)
df_OneHotEncoder

LotShape LandSlope CentralAir  OverallQual
258       Reg       Gtl          Y            7
267       Reg       Mod          Y            5
288       IR1       Gtl          Y            5
649       Reg       Gtl          Y            4
1233      IR1       Gtl          Y            5
167       Reg       Gtl          Y            8
926       Reg       Gtl          Y            8
831       Reg       Gtl          Y            7
1237      IR2       Gtl          Y            7
426       Reg       Mod          Y            7
487       IR1       Gtl          Y            5
375       IR1       Sev          N            1
1126      Reg       Gtl          Y            7
53        IR1       Gtl          Y            9
1033      Reg       Gtl          Y            7

In [40]:

from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
enc.fit(df_OneHotEncoder.iloc[:,0:3])

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=False)

In [41]:
enc.categories_

[array(['IR1', 'IR2', 'Reg'], dtype=object),
 array(['Gtl', 'Mod', 'Sev'], dtype=object),
 array(['N', 'Y'], dtype=object)]

In [45]:
enc.transform(df_OneHotEncoder.iloc[:,0:3])

array([[0., 0., 1., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 1.]])

In [47]:
enc.fit_transform(df_OneHotEncoder.iloc[:,0:3])

array([[0., 0., 1., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 1.]])