<div style='color: #216969;
           background-color: #EAF6F6;
           font-size: 200%;
           border-radius:15px;
           text-align:center;
           font-weight:600;
           border-style: solid;
           border-color: dark green;
           font-family: "Cambria";'>
feature Engingeering ....
<a class="anchor" id="1"></a> 

<img src="https://miro.medium.com/max/1200/1*t8d6pcrhaZ3GZn31Y-U0pA.png" width=500 ></img>
-  Data loading
- features restructuring
- features elelimination

In [3]:
#تحميل البيانات 
import pandas as pd
df= pd.read_csv("../data/HousePrice.csv", index_col=0)

![](../imgs/featureEngin.png)

![](https://image.flaticon.com/icons/png/128/3079/3079166.png)

In [4]:

# object_cols = list(df[df.select_dtypes("object")].index)
list(df.select_dtypes("object").columns)

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallCond  

In [6]:
df.sample(3)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
210  211          30       RL         67.0     5604   Pave   NaN      Reg   
156  157          20       RL         60.0     7200   Pave   NaN      Reg   
659  660          20       RL         75.0     9937   Pave   NaN      Reg   

    LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
210         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
156         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
659         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   

    MoSold YrSold  SaleType  SaleCondition  SalePrice  
210      4   2008        WD         Normal      98000  
156      6   2006        WD         Normal     109500  
659      3   2009        WD         Normal     167000  

[3 rows x 81 columns]

In [7]:
df.select_dtypes(include="number").columns

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='object')

In [8]:
df["TotalSF"] = df["GarageArea"] + df["TotalBsmtSF"]
df["TotalPorchSF"] = df["OpenPorchSF"] + df["EnclosedPorch"] + df["3SsnPorch"] + df["ScreenPorch"]
df["TotalBath"] = df["FullBath"] + df["BsmtFullBath"] + 0.5 * (df["BsmtHalfBath"] + df["HalfBath"])

In [9]:
#  حذف البيانات التي تم ادماجها   
df.drop(["GrLivArea", "TotalBsmtSF" , "OpenPorchSF", "EnclosedPorch", "3SsnPorch", "ScreenPorch" , "FullBath" , 
         "BsmtFullBath", "BsmtHalfBath", "HalfBath"  ], axis=1, inplace=True)

In [10]:
df.head(4)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   

  LandContour Utilities  ... MiscFeature MiscVal MoSold YrSold SaleType  \
0         Lvl    AllPub  ...         NaN       0      2   2008       WD   
1         Lvl    AllPub  ...         NaN       0      5   2007       WD   
2         Lvl    AllPub  ...         NaN       0      9   2008       WD   
3         Lvl    AllPub  ...         NaN       0      2   2006       WD   

  SaleCondition SalePrice  TotalSF  TotalPorchSF  TotalBath  
0        Normal    208500     1404            61        3.5  
1        Normal    181500     1722             0        2.5  
2        Normal    223500     1528            42        3.5  
3       Abnorml    140000     1398           307        2.0  

[4 rows x 74 columns]

## تحديد التصنيفات

In [11]:
# تحديد المتغيرات التي تقل تصنيفاتها على 4 
for col in df.columns:
    if df[col].nunique()< 20:
        print(f" {col} :   {df[col].unique()}  " )

 MSSubClass :   [ 60  20  70  50 190  45  90 120  30  85  80 160  75 180  40]  
 MSZoning :   ['RL' 'RM' 'C (all)' 'FV' 'RH']  
 Street :   ['Pave' 'Grvl']  
 Alley :   [nan 'Grvl' 'Pave']  
 LotShape :   ['Reg' 'IR1' 'IR2' 'IR3']  
 LandContour :   ['Lvl' 'Bnk' 'Low' 'HLS']  
 Utilities :   ['AllPub' 'NoSeWa']  
 LotConfig :   ['Inside' 'FR2' 'Corner' 'CulDSac' 'FR3']  
 LandSlope :   ['Gtl' 'Mod' 'Sev']  
 Condition1 :   ['Norm' 'Feedr' 'PosN' 'Artery' 'RRAe' 'RRNn' 'RRAn' 'PosA' 'RRNe']  
 Condition2 :   ['Norm' 'Artery' 'RRNn' 'Feedr' 'PosN' 'PosA' 'RRAn' 'RRAe']  
 BldgType :   ['1Fam' '2fmCon' 'Duplex' 'TwnhsE' 'Twnhs']  
 HouseStyle :   ['2Story' '1Story' '1.5Fin' '1.5Unf' 'SFoyer' 'SLvl' '2.5Unf' '2.5Fin']  
 OverallQual :   [ 7  6  8  5  9  4 10  3  1  2]  
 OverallCond :   [5 8 6 7 4 2 3 9 1]  
 RoofStyle :   ['Gable' 'Hip' 'Gambrel' 'Mansard' 'Flat' 'Shed']  
 RoofMatl :   ['CompShg' 'WdShngl' 'Metal' 'WdShake' 'Membran' 'Tar&Grv' 'Roll'
 'ClyTile']  
 Exterior1st :   ['Viny

-  Categoty تعديل المتغيرات التصنيفية من كائن إلى تصنيف  

--   $$\large \text { كل القيم التي لا تشهد تغييرا في بيانتها وجب الاستغناء عنها}$$

In [12]:

for col in df.select_dtypes(exclude="number").columns:
  print(f" {col:-<50} :   {df[col].unique()} & Mising Values ( {df[col].isna().sum()/df.shape[0]:.3}) " )

 MSZoning------------------------------------------ :   ['RL' 'RM' 'C (all)' 'FV' 'RH'] & Mising Values ( 0.0) 
 Street-------------------------------------------- :   ['Pave' 'Grvl'] & Mising Values ( 0.0) 
 Alley--------------------------------------------- :   [nan 'Grvl' 'Pave'] & Mising Values ( 0.938) 
 LotShape------------------------------------------ :   ['Reg' 'IR1' 'IR2' 'IR3'] & Mising Values ( 0.0) 
 LandContour--------------------------------------- :   ['Lvl' 'Bnk' 'Low' 'HLS'] & Mising Values ( 0.0) 
 Utilities----------------------------------------- :   ['AllPub' 'NoSeWa'] & Mising Values ( 0.0) 
 LotConfig----------------------------------------- :   ['Inside' 'FR2' 'Corner' 'CulDSac' 'FR3'] & Mising Values ( 0.0) 
 LandSlope----------------------------------------- :   ['Gtl' 'Mod' 'Sev'] & Mising Values ( 0.0) 
 Neighborhood-------------------------------------- :   ['CollgCr' 'Veenker' 'Crawfor' 'NoRidge' 'Mitchel' 'Somerst' 'NWAmes'
 'OldTown' 'BrkSide' 'Sawyer' 

--   $$\large \text { كل القيم التي لا تشهد تغييرا في بيانتها وجب الاستغناء عنها}$$
$$\large \text {جميع البيانات التصنيفية التي لا ترتيب فيها سيتم ترميزها على شكل أعمدة }$$

In [13]:

for col in df.select_dtypes(exclude="number").columns:
  if df[col].nunique()<2:
    print(f" {col:-<30} {df[col].nunique()}")

In [14]:

# MSSubClass متغير تصنيف العقار   
df.MSSubClass.unique()

array([ 60,  20,  70,  50, 190,  45,  90, 120,  30,  85,  80, 160,  75,
       180,  40])

In [15]:
#  المتغيرات المرتبطة بالتواريخ
# YearBuilt, YearRemodAdd , MoSold, YrSold
print(df.MoSold.unique())
print(df.YrSold.unique())

[ 2  5  9 12 10  8 11  4  1  7  3  6]
[2008 2007 2006 2009 2010]


In [16]:
# Processing category dtype is much faster to process
#تكون معالجة البيانات التصنيفية  اسرع

cols=["MSSubClass","YrSold" ]
df[cols]=df[cols].astype("category")

In [17]:
df[cols].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 0 to 1459
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   MSSubClass  1460 non-null   category
 1   YrSold      1460 non-null   category
dtypes: category(2)
memory usage: 15.1 KB


_To better exploit any seasonality in SalePrice, we transform MoSold (which is a cyclical feature)_ 

In [18]:
# http://blog.davidkaleko.com/feature-engineering-cyclical-features.html

import numpy as np
df["SnMoSold"] = np.sin(2 * np.pi * df.MoSold / 12)
df["CsMoSold"] = np.cos(2 * np.pi * df.MoSold / 12)
df.drop("MoSold", axis=1, inplace=True)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 0 to 1459
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype   
---  ------         --------------  -----   
 0   Id             1460 non-null   int64   
 1   MSSubClass     1460 non-null   category
 2   MSZoning       1460 non-null   object  
 3   LotFrontage    1201 non-null   float64 
 4   LotArea        1460 non-null   int64   
 5   Street         1460 non-null   object  
 6   Alley          91 non-null     object  
 7   LotShape       1460 non-null   object  
 8   LandContour    1460 non-null   object  
 9   Utilities      1460 non-null   object  
 10  LotConfig      1460 non-null   object  
 11  LandSlope      1460 non-null   object  
 12  Neighborhood   1460 non-null   object  
 13  Condition1     1460 non-null   object  
 14  Condition2     1460 non-null   object  
 15  BldgType       1460 non-null   object  
 16  HouseStyle     1460 non-null   object  
 17  OverallQual    1460 non-null   int64  

In [21]:
# حفظ البيانات
df.to_csv("../data/HousePrice1.csv")



Assessment :
 أي من التعليمات التالية تمنك من  تحميل ملف :


*   pd.read_csv( ptath/fileName.csv)
*   df.read( path/fileName.csv, index_col=0)

 Dataset أي تعليمة  من التعليمات أدناه تمكن من اظهار جميع حقول جدول البيانات  
 - df.info()
 - df.columns()
 - df.keys()
 - all of the above

حدد التعليمة المناسبة من بين التعليمات أدناه والتي تمكن من اظهار صفوف بيانات بشكل عشوائي


ID ,   Name حدد التعليمة التي تمكن  من تحميل حقلي   
- read_csv(path/fileName, use_cols=["ID", "Name"])

اي تعليمة تمن من إضافة بيانات عشوائية لخاصية جديدة لمجموعة بيانات 
- df["newFeature"]= (b - a) * random_sample() + a



أي تعليمة من بيت التعليمات أدناه تمن من إظهار جميع الخصائص الرقمية لمجموعة بيانات 
- df.select_dtypes(exclude="number").columns

 من   print(f" {col:-<50} :   {df[col].unique()}    : تمكن التعليمة  التالية 
-  screenshot of the result

  df["FeatureName"].unique()  تمكت التعليمة التالية   
 - اظهار القيم التي تحتويها الخاصية دون تكرار
 - 
 - 
  اي تعليمة من بين التعليمات أدناه تكن من حذف خاصية من مجموعة البيانات 
  - df.drop("FeatureName", axis=1, inplace=True)

